#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me
# is redirecting to another page.
# The redirection is a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx
mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 https://nigelomondi.github.io/portfolio/;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
