#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install -y nginx

mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" >/etc/nginx/html/404.html

print %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
   index   index.html;
   location /redirect_me {
        return 301 http://nigelomondi.github.io/portfolio/;
   }
    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-enabled/default
sudo service nginx restart
