#!/usr/bin/env bash
# Configure a new Ubuntu server - web-02 machine.

sudo apt-get update
sudo apt-get install -y nginx

mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root  /var/www/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 https://nigelomondi.github.io/portfolio/;
    }
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
