#!/usr/bin/env bash
# Update the package lists and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy


defaults
    log   global
    mode  http
    option httplog
    option dontlognull
    retries 3
    option redispatch
    timeout connect 5000
    timeout client 10000
    timeout server 10000

frontend lb-frontend
    bind *:80
    default_backend lb-backend


backend lb-backend
    balance roundrobin
    server web-01 100.26.238.151:80 check
    server web-02 100.25.183.127:80 check
EOF

# Enable HAProxy as a service
sudo systemctl enable haproxy

# Start HAProxy
sudo systemctl start haproxy

# Ensure HAProxy is running
sudo systemctl status haproxy

# Output server information
echo "HAProxy is configured to use a round-robin algorithm."
