#!/usr/bin/env bash
# A script that stops 4-to_infinity_and_beyond process
PID=$(pgrep -f "4-to_infinity_and_beyond")

if [ -n "$PID" ]; then
	echo "Stopping 4-to_infinity_and_beyond process with PID $PID"
	kill "$PID"
else
	echo "4-to_infinity_and_beyond process not found"
fi
