#!/usr/bin/env bash
# Display the content of the file /etc/passwd.

# The script should only display:
# username
# user id
# Home directory path for the user

while read -r line;
do
	echo "$line" | cut -d : -f 1,3,6
done < /etc/passwd
