#!/usr/bin/env bash
# Display "Best School" 10n times, for 9th iteration, say hi.

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
		then
			echo "Hi"
		fi
		echo "Best School"
		(( count++ ))
done
