#!/usr/bin/env bash
# This script creates an RSA key pair
# Name of private key - school
# Number of bits - 4096
# Created key must be protected by passphrase - betty
ssh-keygen -t rsa -f school -b 4096 -N betty
